default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: life_development

test:
  <<: *default
  database: life_test

staging:
  <<: *default
  database: life_staging

production:
  <<: *default
  database: life_production
