source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'pg'
gem 'active_model_serializers', '0.10.0.rc2'
gem 'rack-cors', require: 'rack/cors'
gem 'bcrypt', '~> 3.1.7'
gem 'email_validator'

group :development, :test do
  gem 'pry'
  gem 'spring'
end

